sudo: false # use Travis's container-based infrastructure
language: python

python: "3.6"

matrix:
  include:
    - python: "3.8"
      env:
        - TOXENV=py38-without_coverage
    - python: "3.8"
      env:
        - TOXENV=py38-with_coverage
    - python: "3.8"
      arch: arm64
      env:
        - TOXENV=py38-without_coverage
    - python: "3.8"
      arch: arm64
      env:
        - TOXENV=py38-with_coverage


install:
  - case "$TOXENV" in
      pypy3-*)
        curl -sSLO --retry 5 https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.1-linux64.tar.bz2;
        tar -xf pypy3.6-v7.3.1-linux64.tar.bz2;
        mv pypy3.6-v7.3.1-linux64 pypy3;
        ln -s pypy3/bin/pypy3 pypy3/bin/python;
        curl -sSLO --retry 5 https://bootstrap.pypa.io/get-pip.py;
        pypy3/bin/pypy3 get-pip.py;
        ;;
    esac
  - PATH=$(pwd -P)/pypy3/bin:$PATH python -m pip install coveralls virtualenv "tox<3"

script:
  - PATH=$(pwd -P)/pypy3/bin:$PATH tox -v

after_success:
  case "$TOXENV" in
    *with_coverage*)
      PATH=$(pwd -P)/pypy3/bin:$PATH coveralls
      ;;
  esac
